djangotodos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginview, name='login'),
    path('register/', views.register, name='register'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<int:task_id>/', views.taskdetails, name='taskdetails'),
    path('logout/', views.logoutview, name='logout'),
    path('completetask/', views.completetask, name='completetask'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Task (models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    deadline = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from . import models

class CreateTask(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['title', 'description', 'deadline']

tasks/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Task
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from . import forms
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required


def index(request):
    if request.user.is_authenticated:
        return redirect('tasks:tasks')
    else:
        return redirect('tasks:login')


def loginview(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("tasks:tasks")
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("tasks:tasks")
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def taskdetails(request, task_id):
    task = Task.objects.get(id=task_id)
    return render(request, 'taskdetails.html', {'task': task})


@login_required(login_url="/login/")
def tasks(request):
    if request.method == "POST":
        form = forms.CreateTask(request.POST)
        if form.is_valid():
            newtask = form.save(commit=False)
            newtask.author = request.user
            newtask.save()
            return redirect("tasks:tasks")
    else:
        form = forms.CreateTask()
    pending_tasks = Task.objects.filter(author=request.user, completed=False).order_by('-deadline')
    completed_tasks = Task.objects.filter(author=request.user, completed=True).order_by('-id')
    return render(request, 'tasks.html',
                  {'pending_tasks': pending_tasks, 'completed_tasks': completed_tasks, 'form': form})


@login_required(login_url="/login/")
def completetask(request):
    if request.method == "POST":
        updatetask = Task.objects.get(id=request.POST.get('task_id'))
        if (updatetask.author == request.user):
            updatetask.completed = True
            updatetask.save()
            return redirect("tasks:tasks")


def logoutview(request):
    if request.method == "POST":
        logout(request)
        return redirect('tasks:login')

tasks/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col gap-4 justify-between px-3 md:px-12 py-8 md:w-2/3 border-2 border-black mb-8">
    <h2 class="my-auto text-4xl text-light tracking-tighter">login</h2>
    <form class="app-form w-full" action="{% url 'tasks:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        {% endif %}
        <button class="btn mt-4 mr-2">Log In</button>
        <a href="{% url 'tasks:register' %}" class="btn btn-secondary mt-4">I don't have an account</a>
    </form>
</div>
{% endblock %}

tasks/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col gap-4 justify-between px-3 md:px-12 py-8 md:w-2/3 border-2 border-black mb-8">
    <h2 class="my-auto text-4xl text-light tracking-tighter">register</h2>
    <form class="app-form w-full" action="{% url 'tasks:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn mt-4 mr-2">Create new account</button>
        <a href="{% url 'tasks:login' %}" class="btn btn-secondary mt-4">I already have an account</a>
    </form>
</div>
{% endblock %}

tasks/templates/taskdetails.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-5xl tracking-tight mt-8 mb-6">{{ task.title }}</h2>
<p class="text-xl font-light">{{ task.description }}</p>
{% if task.deadline %}
<p class="mt-4">Deadline:</p>
<p class="font-light">{{ task.deadline|date:"d M Y" }} {{ task.deadline|time:"h:i A" }}</p>
{% endif %}
<div class="flex flex-wrap gap-3 mt-8 mb-4">
    <a href="{% url 'tasks:tasks' %}" class="btn">Go Back</a>
    {% if task.completed %}
    <span class="btn btn-success hover:opacity-100" style="cursor: default;">Completed</span>
    {% else %}
    <form class="single-button-form" action="{% url 'tasks:completetask' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="task_id" value="{{ task.id }}"/>
        <button class="btn">Mark as Complete</button>
    </form>
    {% endif %}
</div>
{% endblock %}

tasks/templates/tasks.html
{% extends 'base.html' %}

{% block content %}

<dialog id="add-task-modal">
    <h1 class="text-3xl tracking-tighter">Add new task</h1>
    <form class="app-form" action="{% url 'tasks:tasks' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn mt-2">Add Task</button>
    </form>
</dialog>


<h2 class="text-2xl font-light pb-4 pt-4">pending:</h2>
<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
    {% for task in pending_tasks %}
    <div class="border-2 border-black p-4">
        <div class="flex justify-between item-start">
            <a href="{% url 'tasks:taskdetails' task_id=task.id %}" class="text-2xl tracking-tight cursor-pointer hover:underline">{{ task.title }}</a>
            <form class="single-button-form" action="{% url 'tasks:completetask' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="{{ task.id }}"/>
                <button class="btn">Done</button>
            </form>
        </div>
        {% if task.deadline %}
        <p class="font-light">{{ task.deadline|date:"d M Y" }} {{ task.deadline|time:"h:i A" }}</p>
        {% endif %}
    </div>
    {% empty %}
    <p>No pending tasks.</p>
    {% endfor %}
</div>


<h2 class="text-2xl font-light pb-4 pt-8">completed:</h2>
<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4 opacity-50">
    {% for task in completed_tasks %}
    <div class="border-2 border-black p-4">
        <a href="{% url 'tasks:taskdetails' task_id=task.id %}" class="text-2xl tracking-tight line-through cursor-pointer hover:underline">{{ task.title }}</a>
        {% if task.deadline %}
        <p class="font-light">{{ task.deadline|date:"d M Y" }} {{ task.deadline|time:"h:i A" }}</p>
        {% endif %}
    </div>
    {% empty %}
    <p>No completed tasks.</p>
    {% endfor %}
</div>

<script>
    document.getElementById('add-task-trigger').addEventListener('click', () => {
        document.getElementById('add-task-modal').showModal()
    })
</script>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todos.</title>
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" type="text/tailwindcss" href="{% static 'styles.css' %}"/>
</head>
<body class="bg-retrobeige text-black">
<nav class="container px-4 mx-auto flex justify-between items-end">
    <h1 class="font-extrabold text-7xl md:text-[132px] leading-none pt-8 -mb-2 md:-mb-5 tracking-tighter">todos.</h1>
    {% if user.is_authenticated %}
    <div>
        <button class="btn mr-2" id="add-task-trigger">Add Task</button>
        <form class="single-button-form" action="{% url 'tasks:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger">Logout</button>
        </form>
    </div>
    {% endif %}
</nav>
<div class="[&>div]:h-5">
    <div class="bg-retrored"></div>
    <div class="bg-retroyellow"></div>
    <div class="bg-retrogreen"></div>
    <div class="bg-retroblue"></div>
</div>
<div class="container px-4 mx-auto pt-8">
    {% block content %}
    {% endblock %}
</div>
<script>
    tailwind.config = {
        theme: {
            extend: {
                colors: {
                    retrored: '#FB4834',
                    retroyellow: '#FAB330',
                    retroblue: '#83A598',
                    retrogreen: '#8DC07C',
                    retrobeige: '#F6EEDB'
                },
                fontFamily: {
                    sans: 'Roboto Condensed'
                }
            }
        }
    }
</script>
<style type="text/tailwindcss">
    .btn {
        @apply uppercase text-retrobeige bg-black px-4 py-2 hover:opacity-50 text-sm cursor-pointer;
        box-shadow: 0 0 0 1px #F6EEDB, 0 0 0 2px black;
        margin-bottom: 6px;
    }

    .btn.btn-small {
        @apply text-xs px-3 py-1;
    }

    .btn.btn-danger {
        @apply bg-red-900;
    }

    .btn.btn-secondary {
        @apply bg-neutral-600;
    }

    .btn.btn-success {
        @apply bg-green-900;
    }

    /* Form styles */
    .app-form input {
        @apply w-full p-2 bg-retrobeige border-black border mt-1 mb-2;
    }

    .helptext {
        @apply text-xs;
    }

    .errorlist {
        @apply text-red-900;
    }

    dialog {
        @apply bg-retrobeige px-4 py-6 border-2 border-black;
    }

    ::backdrop {
        @apply bg-black opacity-50;
    }

    textarea {
        @apply bg-retrobeige p-2 w-full border border-black backdrop-opacity-50;
    }

    .single-button-form {
        @apply w-fit inline;
    }
</style>
</body>
</html>